import { Metadata } from "next";
import TopBar from "../components/menu/TopBar";
import { Toaster } from "../components/ui/toaster";
import Container from "../components/ui/container";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex flex-col flex-1 h-screen">
        <TopBar />
        <Container className="mt-4">{children}</Container>
      </div>
      <Toaster />
    </>
  );
}
