import { Metadata } from "next";
import SideBar from "../components/menu/SideBar";
import TopBar from "../components/menu/TopBar";
import { Toaster } from "../components/ui/toaster";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex items-start overflow-hidden">
      <SideBar />
      <div className="flex flex-col flex-1 bg-slate-100 h-screen">
        <TopBar />
        <div className="p-4 overflow-y-auto flex-1">{children}</div>
      </div>
      <Toaster />
    </div>
  );
}
